### ISSUE TITLE
/auto-first

### ISSUE THREAD

**Issue by aeketn** [mcicoria/jqbx-bot-plugins#25]
Toggle the bot to automatically say stats for /first and /first-artist upon a new song playing. 

This would probably be a mod-only feature so that everyone isn't toggling it.

How to implement:

listen to "next-track" and send the "/firsts" command via bot.emit("command:/firsts",input,user,message)

**Comment by mcicoria** [comment]
This is added with just the /first command for now. See `/auto-first` and `/auto-first-gif`.
