### ISSUE TITLE
/config set genres to everynoise.com/engenremap

### ISSUE THREAD

**Issue by trnscndnt** [mcicoria/jqbx-bot-plugins#31]
Genre's can be really broad and would be really convenient to add an algorithm to /config set genres to work with http://everynoise.com/engenremap.html somehow, if that's possible. Thanks!

**Comment by mcicoria** [comment]
Ah yeah. Unfortunately, it's a limitation of the Spotify API. We're limited to sending only the genres that come back from this call: https://developer.spotify.com/web-api/get-recommendations/#available-genre-seeds
