### ISSUE TITLE
Set a playlist for the bot

### ISSUE THREAD

**Issue by mcicoria** [mcicoria/jqbx-bot-plugins#33]
/queue playlist URI

**Comment by ChildishLandrito** [comment]
Any pointers to getting started on this?

**Comment by mcicoria** [comment]
Still testing, so it's not in help yet, but the command is: 
    /queue set spotify:user:markcicoria:playlist:3AImoN1fQDXpzRlCzxO24A

For now needs to be the spotify uri not song link format.

**Comment by gingerbaker1** [comment]
Any chance there's a shuffle option for the bot playlist in the pipeline?

**Comment by mcicoria** [comment]
@gingerbaker1 Already live! 👍 

```/queue shuffle``` will shuffle the current queue.

Information has been added to /help as well. Cheers.

**Comment by gingerbaker1** [comment]
Thank you for reply
