### ISSUE TITLE
Celebrate /first plays

### ISSUE THREAD

**Issue by mcicoria** [mcicoria/jqbx-bot-plugins#46]
/first should send celebratory gifs when a track has not been played. 

https://media3.giphy.com/media/26tOZ42Mg6pbTUPHW/200.gif
"This track has not been played on JQBX."

https://media2.giphy.com/media/3o6gbcjYiGrpaLXy7K/200.gif
"This track has not been played on JQBX."

Ideas for the pool of gifs: /giphy explosions /giphy sirens /giphy glitter poop exploding cake

This should be configurable. Perhaps /config set fancy-firsts on/off

Requested by binary.

**Comment by kylessnell** [comment]
@mcicoria i'd be down to build this. is there a way to hook into if a song is a first from the `next-track` listener?

**Comment by mcicoria** [comment]
This is added with just the /first command for now. See `/auto-first` and `/auto-first-gif`. 

Just for reference to listen to the next track event: 

```
 that.bot.on("next-track", function(data) {
        var track = data.nextTrack;
        // console.log("track is", track);
       

    });


```

**Comment by DejayJD** [comment]
@mcicoria It would be nice if the auto-first feature could be configured so that it only sends messages when the song is a first, instead of sending a message every song. 80% of the time or so, songs are not firsts and it starts to clutter up the chat.
