### ISSUE TITLE
HTML output not working

### ISSUE THREAD

**Issue by franciszekzak** [mcicoria/jqbx-bot-plugins#63]
The output from /help and /hay is broken - it all displays without line breaks, instead of a neat table.

**Comment by Ghoelian** [comment]
Those commands are both working fine for me, in Sea of Metal. Might be a room specific thing?

**Comment by franciszekzak** [comment]
I did some additional testing, and it seems they work in the browser, but not in the desktop mac client.

**Comment by Ghoelian** [comment]
Ahh yeah that would make sense, I don't use the app, just the website.

**Comment by franciszekzak** [comment]
works again.
