### ISSUE TITLE
/up, /queue set [url] not working

### ISSUE THREAD

**Issue by DreamingAmanita** [mcicoria/jqbx-bot-plugins#75]
Hi, as the title says, the commands /up, and all the /queue ones are not working for the bot I have in my room; what to do? 
Thank you!

**Comment by whenimbender** [comment]
Which room are you in? have you tried doing an /update ?

**Comment by DreamingAmanita** [comment]
the room is Dreamer's Nest, after updating the bot multiple times it seems to works fine!

**Comment by whenimbender** [comment]
Cheers, glad its working
