### ISSUE TITLE
Room not syncing for users properly

### ISSUE THREAD

**Issue by JonathanY808** [mcicoria/jqbx-bot-plugins#76]
This may be the wrong area for this, but our **Needles & Grooves** room has had problems for the last 5 days with users having to click sync audio sometimes after every song. If I need to be re-directed to get help on this please let me know.

Thank you!

**Comment by JasonZigelbaum** [comment]
Hey this is a new issue with the Spotify API (see here:
https://github.com/spotify/web-playback-sdk/issues/101#issuecomment-576892889).
It should resolve itself over the next couple of days a workaround for now
is the following:

1. Open the Spotify app on your computer
2. Click the Devices icon on the top right (next to your user image)
3. Select the Spotify App on your computer
4. Now audio should be playing directly from your Spotify app and not the
web player.
5. Audio coming out of your Spotify app does not seem to be effected by
this bug.

Let me know if that helps / any other questions. Sorry about the
inconvenience- wish I could do something about it.

**Comment by JonathanY808** [comment]
Appreciate it! The workaround doesn't seem to be working for me. I even tried to disable JQBX access on the spotify app, log out of spotify everywhere, the log back in thru jqbx, and re-enable app access. Unfortunately, it's still off and on when it comes to syncing with the next pick by whomever is DJ. Hopefully it works itself out soon!
